# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkwrapper',
            name='wraper',
            field=models.CharField(choices=[('PP', 'past papers'), ('PJ', 'practical journals'), ('NT', 'notes')], default='XX', max_length=2),
        ),
    ]
