# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='contributor',
            field=models.CharField(default='Anonymus', max_length=50),
        ),
    ]
