# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-04 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_link_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkwrapper',
            old_name='wraper',
            new_name='wrapper',
        ),
    ]
