# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20180304_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkwrapper',
            name='wrapper',
        ),
    ]
