# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_remove_linkwrapper_wrapper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('IP', 'imp'), ('PP', 'practical program'), ('PT', 'practical theory'), ('BF', 'by faculty'), ('VV', 'verified'), ('CL', 'cool'), ('GH', 'good handwriting')], max_length=2)),
                ('link', models.ManyToManyField(to='subject.Link')),
            ],
        ),
    ]
