# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='tag',
            field=models.ManyToManyField(to='subject.Tag'),
        ),
    ]
